### ISSUE TITLE
Symphony error when no services are selected

### ISSUE THREAD

**Issue by aVandalInShorts** [Solutions-Nitriques/oembed_field#48]
I was frolicing in the yard when suddently I got a Symphony fatal error because I forget to pick a service.

````
Fatal error: Call to undefined method Widget::wrapFormElementWithError() in /home/dev/public_html/mes/extensions/oembed_field/fields/field.oembed.php on line 661
````

**Comment by designermonkey** [comment]
Same here.

**Comment by nitriques** [comment]
John, what version are you using? (both Sym and the extension ?)

This issue should hve been fixed by 676b0194b69c2dbb36f387bd6afcabdbf4dc99b2 since 1.8.5 (and latest is 1.8.7).

**Comment by designermonkey** [comment]
yes, my bad. Sorry.

Nicolas Brassard wrote:

**Comment by nitriques** [comment]
No worries! At least I can close this in peace!
