### ISSUE TITLE
I can't figure out how to display this.

### ISSUE THREAD

**Issue by diomed** [Solutions-Nitriques/oembed_field#50]
Please help me.
I've installed this, and in admin area I see everything displayed, 
video / tweet ... anything supported,
but I don't see anything in front end.

What's the right code for displaying it?

**Comment by nitriques** [comment]
> What's the right code for displaying it?

You need to add it to your Data Source.

After that, everything is visible in the xml. The easiest thing to display it is

````xsl
<xsl:copy-of select="field-name/oembed/html" />
```

**Comment by diomed** [comment]
ok, so I went into get-article.xsl and put that code there.
I also went to Data Sources, and under Content section I've selected oembed.

Saved changes and got this error:
A severe error occurred whilst trying to handle an exception, check the Symphony log for more details
file_get_contents(): Filename cannot be empty on 267 of file /home/u711803242/public_html/symphony/symphony/lib/core/class.errorhandler.php

**Comment by nitriques** [comment]
> ok, so I went into get-article.xsl and put that code there.

You can't simply copy-paste this code. You have to customize the XPath expression to fit the field's name.

> check the Symphony log

What's in the log ? you can get the log by going to /symphony/system/log/

**Comment by nitriques** [comment]
Which Symphony version are you running ?

**Comment by diomed** [comment]
I'm running 2.4 and I didn't simply copy-pasted, but I also replaced field-name to handle: oembed 

It says this for probably all my javascript and css files: 

01/19/2015 7:05 pm > User Notice: FrontendPageNotFoundException 1024 - The page you requested, <code>/workspace/css/demo.css/</code>, does not exist. on line 326 of /home/u711803242/public_html/symphony/symphony/lib/toolkit/class.frontendpage.php

**Comment by nitriques** [comment]
Ok which version of oembed are you using then ?

> It says this for probably all my javascript and css files:

Those are not related to the backend error you mention earlier...

> A severe error occurred whilst trying to handle an exception, check the Symphony log for more details file_get_contents(): Filename cannot be empty on 267 of file home/u711803242/public_html/symphony/symphony/lib/core/class.errorhandler.php

There is nothing related to this in the log ?

**Comment by diomed** [comment]
I am using v. 1.8.6.
just this: 
`01/19/2015 7:10 pm > Warning: GenericErrorHandler 2: file_get_contents(): Filename cannot be empty on line 1178 of file /home/u711803242/public_html/symphony/symphony/content/content.blueprintsdatasources.php
01/19/2015 7:10 pm > UNKNOWN: ErrorException 0 - file_get_contents(): Filename cannot be empty on line 1178 of /home/u711803242/public_html/symphony/symphony/content/content.blueprintsdatasources.php
01/19/2015 7:10 pm > Warning: GenericErrorHandler 2: file_get_contents(): Filename cannot be empty on line 267 of file /home/u711803242/public_html/symphony/symphony/lib/core/class.errorhandler.php
01/19/2015 7:10 pm > Warning: GenericErrorHandler 2: file_get_contents(): Filename cannot be empty on line 267 of file /home/u711803242/public_html/symphony/symphony/lib/core/class.errorhandler.php`

**Comment by nitriques** [comment]
And what the name of the datasouce ? content ?

Are you running a local instance ? Does creating new Data sources works ?

**Comment by nitriques** [comment]
Did you succeed ?

**Comment by diomed** [comment]
no. I'm afraid not :(

**Comment by nitriques** [comment]
Then,
What the name of the Data Source ? Is it content (I assume you're using the default workspace) ?

Are you running a local instance ? Does creating a new Data Source works ?

**Comment by diomed** [comment]
Article is name of Data Source. Yes, it's default workspace. [it's online as a test site on free hosting]
when I click Create Data Source it works. I'm not good with datasources really.

**Comment by nitriques** [comment]
>  I'm not good with datasources really.

If you want to use Symphony, it's one of the basic concepts you'll need to learn. See http://www.getsymphony.com/learn/concepts/view/data-sources/

Can you check the permissions on the workspace/data-source folder + data.8 files ?

**Comment by diomed** [comment]
data sources folder is 0755
and files inside are 0644

**Comment by diomed** [comment]
It appears I indeed can not create  new data sources.
When I click on Create Data Source it leads me to same error again.

**Comment by nitriques** [comment]
Can you check if the symphony/template folder is readable ? And properly uploaded ?

**Comment by diomed** [comment]
I've checked,  and you've found my error. It wasn't. It was inside lib directory. 
I must have moved it accidentally. 

Now I went back, selected oembed and there is no error. 
Doesn't display still.

**Comment by nitriques** [comment]
At least we have one problem fixed.

Can you please check if the oembed data is in the xml ? (with ?debug)

**Comment by diomed** [comment]
when I got to article and put ?debug I see it there.
tho, when I go on main page that lists articles and look for it i don't see it anywhere

**Comment by nitriques** [comment]
> when I got to article and put ?debug I see it there.

Yo see it in the xml ? If so, there an xpath error.

**Comment by diomed** [comment]
I'm not sure what that means, and have no idea what I need to do to fix that kind of error.

**Comment by nitriques** [comment]
Adding `?debug` should display the resulting xml of the page. Please check if oembed's xml is present in there.

If you do not know xpath, well, you must learn it to use Symphony because the template engine is XSLT.

**Comment by diomed** [comment]
could you please come on twitter so I could send you login data so 
you could check out what's wrong, fix it and tell me what did I do wrong? please.

**Comment by nitriques** [comment]
You can send it to open-source (at) deuxhuithuit (.) com

Or hit me up on keybase.io if you want to encrypt your message. I have invites for keybase.io if you do not have an account.

**Comment by nitriques** [comment]
I've replied to your email. I've fixed the issues.

But sorry, I also made a mistake. The right XSLT code is

```
<xsl:value-of select="oembed/oembed/html" disable-output-escaping="yes" />
```

**Comment by diomed** [comment]
I know you've solved this for me, for which I'm very grateful.
I still believe that Installation part of README.md is not very straightforward
and should include more info that you've helped me with, for beginners who want 
to install this pretty essential extension.

Also, can multiple instances of this field be used?
Like multiple providers on one post.

**Comment by nitriques** [comment]
> I know you've solved this for me, for which I'm very grateful.

My pleasure!

> I still believe that Installation part of README.md is not very straightforward

Which README ? oembed field's ? All fields works the same way in Symphony. Check this out http://www.getsymphony.com/learn/concepts/view/fields/ The learn section of the site as everything you need.

> Also, can multiple instances of this field be used? Like multiple providers on one post.

Yes totally!

**Comment by diomed** [comment]
they must have different handle then, right?

I'm not talking about fields itself but of part which doesn't explain how and where
to actually enter proper xslt code to display it on front end, which is essential.
What I'm asking really is explanation for end user, not for coders/developers.

**Comment by nitriques** [comment]
> they must have different handle then, right?

Yes.

> What I'm asking really is explanation for end user, not for coders/developers.

Symphony is not for meant to be installed nor customized by end user, it's for web developers/ web designers.

Symphony can/is used by end user to manage content only. You need to learn how to code XSLT to be able to customize it.

Docuementation for developers is available on Symphony's website: http://www.getsymphony.com/learn/concepts/ 
http://www.getsymphony.com/learn/concepts/view/xslt/
