### ISSUE TITLE
Switch Twitter to JSON

### ISSUE THREAD

**Issue by niallkennedy** [Solutions-Nitriques/oembed_field#52]
Twitter will [remove support for the XML oEmbed response format on May 1](https://twittercommunity.com/t/deprecation-of-xml-response-type-for-single-tweet-oembed/62013). Update [the Twitter service driver](https://github.com/Solutions-Nitriques/oembed_field/blob/master/lib/drivers/class.serviceTwitter.php) to the new JSON oEmbed endpoint.

* oEmbedApiUrl base URI changes to `https://publish.twitter.com/oembed?url=`
* getAPIFormat should return json
* the endpoint supports TLS (return true from supportsSSL?)

**Comment by nitriques** [comment]
> the endpoint supports TLS (return true from supportsSSL?)

supportsSSL means that the oembed media is served over SSL/TLS. 

Since `oEmbedApiUrl` always contains the https prefix, we do not need to check for `supportsSSL` for that.

But hey, thanks!
